name: dx workflow


on:
  push:
    branches: [poc/**]
    # Only trigger a workflow when changes have been made to files in the below mentioned path.
    # paths:
    #   - "poc/**"
env:
  SF_QA_ORG__AUTH_URL: ${{ secrets.SF_QA_ORG__AUTH_URL }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  Validate_To_QA:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #Choose the docker image from which the container should be created
    # container:
    #   image: dreddy/sfdx-git-delta:latest
    #   options: --user 0:0 --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      # - run: git fetch --prune --unshallow --tags

      # - name: Authorize Org
      #   run: |
      #     echo $SF_QA_ORG__AUTH_URL > authURLFile
      #     sfdx force:auth:sfdxurl:store -f authURLFile -s -a QA
      # - name: Deployment
      #   run: |
      #     sfdx force:source:deploy -p force-app --checkonly
